// <auto-generated />
using System;
using Digital_Test.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Digital_Test.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20210707220006_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Digital_Test.Entities.Cliente", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Digital_Test.Entities.Detalle_Factura", b =>
                {
                    b.Property<int>("Id_DetalleFact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("FacturaId_Factura")
                        .HasColumnType("int");

                    b.Property<int>("Id_Factura")
                        .HasColumnType("int");

                    b.Property<int>("Id_Producto")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Unitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoId_Producto")
                        .HasColumnType("int");

                    b.HasKey("Id_DetalleFact");

                    b.HasIndex("FacturaId_Factura");

                    b.HasIndex("ProductoId_Producto");

                    b.ToTable("Detalle_Facturas");
                });

            modelBuilder.Entity("Digital_Test.Entities.Factura", b =>
                {
                    b.Property<int>("Id_Factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId_Cliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Factura");

                    b.HasIndex("ClienteId_Cliente");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Digital_Test.Entities.Producto", b =>
                {
                    b.Property<int>("Id_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Producto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Digital_Test.Entities.Detalle_Factura", b =>
                {
                    b.HasOne("Digital_Test.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId_Factura");

                    b.HasOne("Digital_Test.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId_Producto");
                });

            modelBuilder.Entity("Digital_Test.Entities.Factura", b =>
                {
                    b.HasOne("Digital_Test.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId_Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
